version: '3.1'

services:
  app:
    image: 1b50d0175132
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=root
      - DB_PASSWORD=
      - DB.URL=jdbc:mysql://db:3306/users
    depends_on:
      - db
  db:
    image: 'mysql'
    container_name: db
    expose:
      - '3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

